### ISSUE TITLE
CRM

### ISSUE THREAD

**Issue by farokovic** [Odoo-mobile/crm#36]
Hello
The syncronisation between mobile and serveur in the customers part, it synchronize only from mobile to serveur. When I create a customer in the server it didn't appear in odoo mobile.

**Comment by beltrewilton** [comment]
Hi, 
To me is working with just swype on the list.

**Comment by beltrewilton** [comment]
I have noticed that customers are only displayed if they have an iteration of sale or otherwise, but if you look at the mobile app you can find this ... through magnifier...

**Comment by dpr-odoo** [comment]
Yes, Exactly @beltrewilton you are right.

By default automatically it will bring the customers which are related to your sales orders, leads/opportunity. 
Then also, by searching you can get customers from server. :+1: 

One more advantage is, you can import customer in your phone's contact book.
