### ISSUE TITLE
stucks on "Logging in..."

### ISSUE THREAD

**Issue by nacho22martin** [Odoo-mobile/crm#38]
I'm trying to connect to a self-hosted server (odoo.mysterysur.com.ar:8069) and after i put my login information, it gets me a "logging in..." message, finally shows a  "creating account..."message  and crached.

**Comment by nacho22martin** [comment]
my device is samsung s3 android 4.3

**Comment by dpr-odoo** [comment]
Can you please update app version from 1.0.4 to 1.0.5 we fix major issues for version 7 and 8.saas~6, thanks
