### ISSUE TITLE
Odoo CRM Launch

### ISSUE THREAD

**Issue by mathi123** [Odoo-mobile/crm#4]
When will Odoo mobile CRM be available in Google Play?

In June 2014 it was announced to be released within a months or so.

https://www.odoo.com/forum/help-1/question/odoo-mobile-crm-launch-60033

Regards,

**Comment by watermelonjuice** [comment]
It's been released.

**Comment by mathi123** [comment]
Super!

**Comment by beltrewilton** [comment]
Nice!

2015-03-18 6:41 GMT-04:00 Mathias Colpaert <notifications@github.com>:
