### ISSUE TITLE
Day of month and weekday mismatching

### ISSUE THREAD

**Issue by taifu** [Odoo-mobile/crm#45]
The image says everything: today is thursday 16th but Odoo Mobile shows it as wednesday 16th.
Perhaps a 0-based day of week issue?

![screenshot_2015-04-16-11-43-51](https://cloud.githubusercontent.com/assets/115712/7178541/dce01484-e42f-11e4-8a82-a1648f790775.png)

**Comment by michaelkarrer81** [comment]
+1 very same for me and all my tester here in austria

**Comment by alejandrosantana** [comment]
Verified. Day name is wrong.

**Comment by dpr-odoo** [comment]
Issue fixed in last commit : https://github.com/Odoo-mobile/crm/commit/b25516b8f745cb840705f16ba5d2f47bcad897af Update will available soon on play store.
